language: csharp

addons:
  apt:
    packages:
      - wine

env:
  - NODE_VERSION="4.2"
  - NODE_VERSION="0.12"
  - NODE_VERSION="0.10"

before_install:
  - nvm install $NODE_VERSION
  - npm install -g grunt-cli

install:
  - npm install

script:
  - npm test
